package com.wanfin.fpd.modules.repayplan.vo;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.wanfin.fpd.modules.repayplan.entity.TRepayPlan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PlanCreateParam implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public PlanCreateParam() {
	}
	private String dealType;//处理类型，为new是重新生成，否则以读取历史记录为先，不保存到数据库
	private String businessId;//业务类型
	private String businessType;//业务类型
	private BigDecimal amount;//贷款金额   //double #3121
	private String loanRateType;//利率类型  add by shif  #3121 原没有获取利率类型，kie只获取年利率 1年  2月  3日  
	private BigDecimal loanRate;//利率      //float #3121
	//private int loanPeriod;//期限
	private String loanPeriod;//期限
	private String loanDate;//放款日
	private String payType;//还款方式    1|2|3 = 等额本息|等额本金|按月付息到期还款
	private String periodType;//还款周期 （payType=3时才会用到，等额本息和等额本金周期只能是“月”） 1|2|3  = 年|月|日
	private String payDay;//每期还款日期 （payType=3时才会用到，等额本息和等额本金的还款日只能是放款日）	为null默认为放款日
	private String payOptions;//还款选项 （payType=3时才会用到）	1|2|null = 前置付息|一次性付息|常规
	
	private String payPrincipalDate;//最后还本金日期
	private String ifRealityDay;//是否按照大小月
	private int unPayPeriod;//未还期数
	
	private BigDecimal payAmount;//提前还款金额   //double #3121
	private String payDate;//提前还款时间
	private List<TRepayPlan> list;//还款计划

	private Integer extendDays;//展期天数
	
	public String getBusinessId() {
		return businessId;
	}
	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}
	public String getBusinessType() {
		return businessType;
	}
	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}
	public BigDecimal getAmount() {
		return amount;
	}
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	public BigDecimal getLoanRate() {
		return loanRate;
	}
	public void setLoanRate(BigDecimal loanRate) {
		this.loanRate = loanRate;
	}
	public String getLoanPeriod() {
		return loanPeriod;
	}
	public void setLoanPeriod(String loanPeriod) {
		this.loanPeriod = loanPeriod;
	}
	
	public String getDealType() {
		return dealType;
	}
	public void setDealType(String dealType) {
		this.dealType = dealType;
	}
	public String getLoanDate() {
		return loanDate;
	}
	public void setLoanDate(String loanDate) {
		this.loanDate = loanDate;
	}
	public String getPayType() {
		return payType;
	}
	public void setPayType(String payType) {
		this.payType = payType;
	}
	public String getPeriodType() {
		return periodType;
	}
	public void setPeriodType(String periodType) {
		this.periodType = periodType;
	}
	public String getPayDay() {
		return payDay;
	}
	public void setPayDay(String payDay) {
		this.payDay = payDay;
	}
	public String getPayOptions() {
		return payOptions;
	}
	public void setPayOptions(String payOptions) {
		this.payOptions = payOptions;
	}
	public int getUnPayPeriod() {
		return unPayPeriod;
	}
	public void setUnPayPeriod(int unPayPeriod) {
		this.unPayPeriod = unPayPeriod;
	}
	public BigDecimal getPayAmount() {
		return payAmount;
	}
	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}
	public String getPayDate() {
		return payDate;
	}
	public void setPayDate(String payDate) {
		this.payDate = payDate;
	}
	public List<TRepayPlan> getList() {
		return list;
	}
	public void setList(List<TRepayPlan> list) {
		this.list = list;
	}
	public String getLoanRateType() {
		return loanRateType;
	}
	public void setLoanRateType(String loanRateType) {
		this.loanRateType = loanRateType;
	}
	public String getPayPrincipalDate() {
		return payPrincipalDate;
	}
	public void setPayPrincipalDate(String payPrincipalDate) {
		this.payPrincipalDate = payPrincipalDate;
	}
	public String getIfRealityDay() {
		return ifRealityDay;
	}
	public void setIfRealityDay(String ifRealityDay) {
		this.ifRealityDay = ifRealityDay;
	}
	public Integer getExtendDays() {
		return extendDays;
	}
	public void setExtendDays(Integer extendDays) {
		this.extendDays = extendDays;
	}
	
	
}